name: Build Custom RouterOS v7

on:
  workflow_dispatch:
    inputs:
      INPUT_VERSION:
        description: 'Input VERSION CODE (e.g., 7.1.1)'
        required: true
        default: '7.17.1'

permissions:
  contents: write

env:
  MIKRO_NPK_SIGN_PUBLIC_KEY: ${{ secrets.MIKRO_NPK_SIGN_PUBLIC_KEY }}
  MIKRO_LICENSE_PUBLIC_KEY: ${{ secrets.MIKRO_LICENSE_PUBLIC_KEY }}
  CUSTOM_NPK_SIGN_PRIVATE_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PRIVATE_KEY }}
  CUSTOM_NPK_SIGN_PUBLIC_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PUBLIC_KEY }}
  CUSTOM_LICENSE_PRIVATE_KEY: ${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}
  CUSTOM_LICENSE_PUBLIC_KEY: ${{ secrets.CUSTOM_LICENSE_PUBLIC_KEY }}
  LATEST_VERSION: "${{ github.event.inputs.INPUT_VERSION }}"
  
jobs:
  Build_Custom_ROS_v7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Get latest version
      id: get_latest
      run: |
        echo $(uname -a)
        LATEST_VERSION="${{ github.event.inputs.INPUT_VERSION }}"
        echo Latest Version:$LATEST_VERSION
        if [ "${{ github.event_name }}" == "schedule" ]; then
          _LATEST_VERSION="${{ github.event.inputs.INPUT_VERSION }}"
          if [ "$_LATEST_VERSION" == "$LATEST_VERSION" ]; then
            echo "No new version found"
            echo "has_new_version=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        echo "has_new_version=true" >> $GITHUB_OUTPUT
        curl -s -o CHANGELOG https://upgrade.mikrotik.com/routeros/$LATEST_VERSION/CHANGELOG
        cat CHANGELOG
        echo "NEWEST=${NEWEST}" >> $GITHUB_ENV
        echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          if [ "${{ matrix.arch }}" == "x86" ]; then
          ARCH=''
        elif [ "${{ matrix.arch }}" == "arm" ]; then
          ARCH='-arm'
        elif [ "${{ matrix.arch }}" == "arm64" ]; then
          ARCH='-arm64'
        elif [ "${{ matrix.arch }}" == "mipsbe" ]; then
          ARCH='-mipsbe'
        elif [ "${{ matrix.arch }}" == "mmips" ]; then
          ARCH='-mmips'
        elif [ "${{ matrix.arch }}" == "smips" ]; then
          ARCH='-smips'
        elif [ "${{ matrix.arch }}" == "tile" ]; then
          ARCH='-tile'
        elif [ "${{ matrix.arch }}" == "ppc" ]; then
          ARCH='-ppc'
        fi
        echo "ARCH=$ARCH" >> $GITHUB_ENV
        sudo apt-get update > /dev/null

    - name: Cache mikrotik-${{ env.LATEST_VERSION }}${{ env.ARCH }}.iso
      if: steps.get_latest.outputs.has_new_version == 'true' && (matrix.arch == 'x86' || matrix.arch == 'arm64')
      id: cache_mikrotik
      uses: actions/cache@v4
      with:
        path: mikrotik.iso
        key: mikrotik-${{ env.LATEST_VERSION }}-${{ matrix.arch }}

    - name: Get mikrotik-${{ env.LATEST_VERSION }}${{ env.ARCH }}.iso
      if: steps.get_latest.outputs.has_new_version == 'true' && steps.cache_mikrotik.outputs.cache-hit != 'true' && (matrix.arch == 'x86' || matrix.arch == 'arm64')
      run: |
        sudo curl -s -o mikrotik.iso https://download.mikrotik.com/routeros/$LATEST_VERSION/mikrotik-$LATEST_VERSION$ARCH.iso

    - name: Patch mikrotik-${{ env.LATEST_VERSION }}${{ env.ARCH }}.iso
      if: steps.get_latest.outputs.has_new_version == 'true' && (matrix.arch == 'x86' || matrix.arch == 'arm64')
      run: |
        sudo apt-get install -y mkisofs xorriso --no-install-recommends > /dev/null
        sudo mkdir iso
        sudo mount -o loop,ro mikrotik.iso iso/
        sudo mkdir new_iso
        sudo cp -r iso/* new_iso/
        sudo rsync -a iso/ new_iso/
        sudo umount iso/
        sudo rm -rf iso/
        NPK_FILES=$(find new_iso/*.npk)
        for file in $NPK_FILES; do
          sudo -E python3 patch.py npk $file
        done
        sudo cp new_iso/routeros-$LATEST_VERSION*.npk routeros-$LATEST_VERSION$ARCH-OEM.npk
        sudo mkdir efiboot
        sudo mount -o loop new_iso/efiboot.img efiboot/
        if [ "${{ matrix.arch }}" == "x86" ]; then
          sudo -E python3 patch.py kernel efiboot/linux.x86_64
          sudo cp efiboot/linux.x86_64 new_iso/isolinux/linux
          sudo umount efiboot/
          sudo mkisofs -o mikrotik-$LATEST_VERSION$ARCH-OEM.iso \
                       -V "MikroTik $LATEST_VERSION $ARCH" \
                       -sysid "" -preparer "MiKroTiK" \
                       -publisher "" -A "MiKroTiK RouterOS" \
                       -input-charset utf-8 \
                       -b isolinux/isolinux.bin \
                       -c isolinux/boot.cat \
                       -no-emul-boot \
                       -boot-load-size 4 \
                       -boot-info-table \
                       -eltorito-alt-boot \
                       -e efiboot.img \
                       -no-emul-boot \
                       -R -J \
                       new_iso/
        elif [ "${{ matrix.arch }}" == "arm64" ]; then
          sudo -E python3 patch.py kernel efiboot/EFI/BOOT/BOOTAA64.EFI
          sudo umount efiboot/
          sudo xorriso -as mkisofs -o mikrotik-$LATEST_VERSION$ARCH-OEM.iso \
                       -V "MikroTik $LATEST_VERSION ${{ matrix.arch }}" \
                       -sysid "" -preparer "MiKroTiK" \
                       -publisher "" -A "MiKroTiK RouterOS" \
                       -input-charset utf-8 \
                       -b efiboot.img \
                       -no-emul-boot \
                       -R -J \
                       new_iso/
        fi
        sudo rm -rf efiboot/
        sudo mkdir all_packages_iso$ARCH-$LATEST_VERSION
        sudo cp new_iso/*.npk all_packages_iso$ARCH-$LATEST_VERSION/
        sudo rm -rf new_iso/
        cd all_packages_iso$ARCH-$LATEST_VERSION/
        sudo zip ../all_packages$ARCH-$LATEST_VERSION-OEM.zip *.npk
        cd ../

    - name: Cache refind
      if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86'
      id: cache_refind
      uses: actions/cache@v4
      with:
        path: refind-bin-0.14.2.zip
        key: refind

    - name: Get refind
      if: steps.get_latest.outputs.has_new_version == 'true' && steps.cache_refind.outputs.cache-hit != 'true' && matrix.arch == 'x86'
      run: |
        sudo curl -s -o refind-bin-0.14.2.zip https://nchc.dl.sourceforge.net/project/refind/0.14.2/refind-bin-0.14.2.zip

    - name: Cache install-image-${{ env.LATEST_VERSION }}${{ env.ARCH }}.zip
      if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86'
      id: cache_install_image
      uses: actions/cache@v4
      with:
        path: install-image.zip
        key: install-image-${{ env.LATEST_VERSION }}-${{ matrix.arch }}

    - name: Get install-image-${{ env.LATEST_VERSION }}${{ env.ARCH }}.zip
      if: steps.get_latest.outputs.has_new_version == 'true' && steps.cache_install_image.outputs.cache-hit != 'true' && matrix.arch == 'x86'
      run: |
        sudo curl -s -o install-image.zip https://download.mikrotik.com/routeros/$LATEST_VERSION/install-image-$LATEST_VERSION.zip

    - name: Patch install-image-${{ env.LATEST_VERSION }}${{ env.ARCH }}.img
      if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86'
      run: |
        sudo apt-get install -y qemu-utils extlinux --no-install-recommends > /dev/null
        sudo unzip install-image.zip
        sudo modprobe nbd
        sudo qemu-nbd -c /dev/nbd0 -f raw install-image-$LATEST_VERSION.img
        sudo mkdir install-image
        sudo mount /dev/nbd0 install-image/
        sudo unzip refind-bin-0.14.2.zip refind-bin-0.14.2/refind/refind_x64.efi
        sudo cp refind-bin-0.14.2/refind/refind_x64.efi install-image/EFI/BOOT/BOOTX64.EFI
        sudo rm -rf refind-bin-0.14.2
        sudo -E python3 patch.py kernel install-image/linux
        NPK_FILES=$(find install-image/*.npk)
        for file in $NPK_FILES; do
          sudo -E python3 patch.py npk $file
        done
        sudo umount /dev/nbd0
        sudo qemu-nbd -d /dev/nbd0
        sudo rm -rf install-image/
        sudo mv install-image-$LATEST_VERSION.img install-image-$LATEST_VERSION$ARCH-OEM.img
        sudo zip install-image-$LATEST_VERSION$ARCH-OEM.img.zip install-image-$LATEST_VERSION$ARCH-OEM.img

    - name: Cache routeros-${{ env.LATEST_VERSION }}${{ env.ARCH }}.npk & all_packages${{ env.ARCH }}-${{ env.LATEST_VERSION }}.zip
      if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch != 'x86'
      id: cache_routeros_npk
      uses: actions/cache@v4
      with:
        path: |
          routeros-${{ env.LATEST_VERSION }}${{ env.ARCH }}.npk
          all_packages${{ env.ARCH }}-${{ env.LATEST_VERSION }}.zip
        key: routeros-${{ env.LATEST_VERSION }}-${{ matrix.arch }}

    - name: Get routeros-${{ env.LATEST_VERSION }}${{ env.ARCH }}.npk & all_packages${{ env.ARCH }}-${{ env.LATEST_VERSION }}.zip
      if: steps.get_latest.outputs.has_new_version == 'true' && steps.cache_routeros_npk.outputs.cache-hit != 'true' && matrix.arch != 'x86'
      run: |
        sudo curl -s -o routeros-$LATEST_VERSION$ARCH.npk https://download.mikrotik.com/routeros/$LATEST_VERSION/routeros-$LATEST_VERSION$ARCH.npk
        sudo curl -s -o all_packages$ARCH-$LATEST_VERSION.zip https://download.mikrotik.com/routeros/$LATEST_VERSION/all_packages$ARCH-$LATEST_VERSION.zip

    - name: Patch routeros-${{ env.LATEST_VERSION }}${{ env.ARCH }}.npk & all_packages${{ env.ARCH }}-${{ env.LATEST_VERSION }}.zip
      if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch != 'x86'
      run: |
        sudo mkdir all_packages$ARCH-$LATEST_VERSION
        sudo unzip all_packages$ARCH-$LATEST_VERSION.zip -d all_packages$ARCH-$LATEST_VERSION/
        sudo cp routeros-$LATEST_VERSION$ARCH.npk routeros-$LATEST_VERSION$ARCH-OEM.npk
        sudo -E python3 patch.py npk routeros-$LATEST_VERSION$ARCH-OEM.npk
        NPK_FILES=$(find all_packages$ARCH-$LATEST_VERSION/*.npk)
        for file in $NPK_FILES; do
          sudo -E python3 npk.py sign $file $file
        done
        cd all_packages$ARCH-$LATEST_VERSION/
        sudo zip ../all_packages$ARCH-$LATEST_VERSION-OEM.zip *.npk
        cd ..
        sudo rm -rf all_packages$ARCH-$LATEST_VERSION/

    - name: Update latest version
      if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86'
      run: |
        echo $NEWEST > latest7.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add latest7.txt
        git commit -m "Update latest version"
        git push

    - name: Create Release tag ${{ env.LATEST_VERSION }}
      if: steps.get_latest.outputs.has_new_version == 'true'
      uses: softprops/action-gh-release@v2
      with:
        name: "RouterOS ${{ env.LATEST_VERSION }}"
        body_path: "CHANGELOG"
        tag_name: ${{ env.LATEST_VERSION }}
        make_latest: true
        files: |
          mikrotik-${{ env.LATEST_VERSION }}${{ env.ARCH }}-OEM.iso
          install-image-${{ env.LATEST_VERSION }}${{ env.ARCH }}-OEM.*.zip
          routeros-${{ env.LATEST_VERSION }}${{ env.ARCH }}-OEM.npk
          all_packages*-${{ env.LATEST_VERSION }}-OEM.zip
