name: Generate Lic Key

on:
  workflow_dispatch:
    inputs:
      license_key:
        description: 'Input license key (e.g., SGPJ-7SKL)'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  Gen_Lic_Key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Generate License
      id: generate_license
      run: |
        python3 license.py licgenros ${{ github.event.inputs.license_key }} 9DBC845E9018537810FDAE62824322EEE1B12BAD81FCA28EC295FB397C61CE0B > ${{ github.event.inputs.license_key }}.key

    - name: Ensure License Keys Directory Exists
      run: |
        mkdir -p "License Keys"

    - name: Move and Commit License Key File
      run: |
        mv "${{ github.event.inputs.license_key }}.key" "License Keys/"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "License Keys/${{ github.event.inputs.license_key }}.key"
        git commit -m "Add license key file: License Keys/${{ github.event.inputs.license_key }}.key"
        git push
